source "http://rubygems.org"
source "http://sulair-rails-dev.stanford.edu"

gem "moab-versioning", ">=0.8.6" #:path => '/Users/rnanders/Code/Ruby/moab-versioning'
gem "active-fedora"
gem "bagit"
gem "fakeweb"
gem "jettywrapper"
gem "nokogiri"
gem "rake", ">=0.8.7"
gem "rest-client"
gem "confstruct"
gem "dor-services"
gem "lyber-core"
gem "druid-tools"
gem "rspec", "> 2"
gem "rcov"
gem "yard"
gem "equivalent-xml"
