register-sdr:
   batch_limit: 1000
   error_limit: 5

transfer-object:
  prerequisite: register-sdr  
  batch_limit: 1000
  error_limit: 5
  
populate-metadata:
  prerequisite: transfer-object  
  batch_limit: 1000
  error_limit: 5