development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@sdr-fedora-dev.stanford.edu/fedora
  solr:
    url: http://sdr2admin-dev.stanford.edu/sdrsolr/sdr2-development/
test:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://127.0.0.1:8983/solr/test
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@sdr-fedora-dev.stanford.edu/fedora
  solr:
    url: http://sdr2admin-dev.stanford.edu/sdrsolr/sdr2-development/
    
