require 'sdr_ingest/register_sdr'
require 'sdr_ingest/transfer_object'
require 'sdr_ingest/validate_bag'
require 'sdr_ingest/verify_agreement'
require 'sdr_ingest/complete_deposit'
require 'sdr_ingest/update_catalog'
require 'sdr_ingest/ingest_cleanup'
